/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AppConfigRouteImport } from './routes/app-config'
import { Route as AppChatApiRouteImport } from './routes/app-chat-api'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCreditsRouteImport } from './routes/app.credits'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppChatIndexRouteImport } from './routes/app.chat.index'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/app-config',
  path: '/app-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatApiRoute = AppChatApiRouteImport.update({
  id: '/app-chat-api',
  path: '/app-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/app': typeof AppRouteWithChildren
  '/app-chat-api': typeof AppChatApiRoute
  '/app-config': typeof AppConfigRoute
  '/company': typeof CompanyRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/economy': typeof EconomyRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/runtime': typeof RuntimeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workers': typeof WorkersRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/credits': typeof AppCreditsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/login': typeof AppLoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/app-chat-api': typeof AppChatApiRoute
  '/app-config': typeof AppConfigRoute
  '/company': typeof CompanyRoute
  '/developers': typeof DevelopersRoute
  '/economy': typeof EconomyRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/runtime': typeof RuntimeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workers': typeof WorkersRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/login': typeof AppLoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/app': typeof AppRouteWithChildren
  '/app-chat-api': typeof AppChatApiRoute
  '/app-config': typeof AppConfigRoute
  '/company': typeof CompanyRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/economy': typeof EconomyRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/runtime': typeof RuntimeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workers': typeof WorkersRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/credits': typeof AppCreditsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/login': typeof AppLoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/app'
    | '/app-chat-api'
    | '/app-config'
    | '/company'
    | '/developers'
    | '/docs'
    | '/economy'
    | '/manifesto'
    | '/pricing'
    | '/product'
    | '/runtime'
    | '/sitemap.xml'
    | '/workers'
    | '/app/chat'
    | '/app/credits'
    | '/app/dashboard'
    | '/app/login'
    | '/app/settings'
    | '/docs/$slug'
    | '/app/'
    | '/docs/'
    | '/app/chat/$id'
    | '/app/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/app-chat-api'
    | '/app-config'
    | '/company'
    | '/developers'
    | '/economy'
    | '/manifesto'
    | '/pricing'
    | '/product'
    | '/runtime'
    | '/sitemap.xml'
    | '/workers'
    | '/app/credits'
    | '/app/dashboard'
    | '/app/login'
    | '/app/settings'
    | '/docs/$slug'
    | '/app'
    | '/docs'
    | '/app/chat/$id'
    | '/app/chat'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/app'
    | '/app-chat-api'
    | '/app-config'
    | '/company'
    | '/developers'
    | '/docs'
    | '/economy'
    | '/manifesto'
    | '/pricing'
    | '/product'
    | '/runtime'
    | '/sitemap.xml'
    | '/workers'
    | '/app/chat'
    | '/app/credits'
    | '/app/dashboard'
    | '/app/login'
    | '/app/settings'
    | '/docs/$slug'
    | '/app/'
    | '/docs/'
    | '/app/chat/$id'
    | '/app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  AppRoute: typeof AppRouteWithChildren
  AppChatApiRoute: typeof AppChatApiRoute
  AppConfigRoute: typeof AppConfigRoute
  CompanyRoute: typeof CompanyRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRouteWithChildren
  EconomyRoute: typeof EconomyRoute
  ManifestoRoute: typeof ManifestoRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  RuntimeRoute: typeof RuntimeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-config': {
      id: '/app-config'
      path: '/app-config'
      fullPath: '/app-config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-chat-api': {
      id: '/app-chat-api'
      path: '/app-chat-api'
      fullPath: '/app-chat-api'
      preLoaderRoute: typeof AppChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credits': {
      id: '/app/credits'
      path: '/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatIdRoute: typeof AppChatIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatIdRoute: AppChatIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
  AppCreditsRoute: typeof AppCreditsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
  AppCreditsRoute: AppCreditsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  AppRoute: AppRouteWithChildren,
  AppChatApiRoute: AppChatApiRoute,
  AppConfigRoute: AppConfigRoute,
  CompanyRoute: CompanyRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRouteWithChildren,
  EconomyRoute: EconomyRoute,
  ManifestoRoute: ManifestoRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  RuntimeRoute: RuntimeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
